import { createStore } from 'vuex'
import auth from './auth'

export default createStore({
	state: {
		orders: [
			{
				id: 1,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 2,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 3,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 4,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 5,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 6,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 7,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 8,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 9,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 10,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 11,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 12,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 13,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 14,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 15,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 16,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 17,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 18,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 19,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 20,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 21,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 22,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 23,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 24,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 25,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 26,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 27,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 28,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 29,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 30,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 31,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 32,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 33,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 34,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 1,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 2,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 3,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 4,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 5,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 6,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 7,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 8,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 9,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 10,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 11,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 12,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 13,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 14,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 15,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 16,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 17,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 18,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 19,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 20,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 21,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 22,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 23,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 24,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 25,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 26,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 27,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 28,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 29,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 30,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 31,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 32,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
			{
				id: 33,
				date: '16.10.22',
				time: '14:14',
				title: 'Осенний Валаам из Сортавала',
				persons: 1,
				amount: 6529,
				paymentType: 'Стандартная',
				status: 'Оплачено',
				qrcode: '#',
			},
			{
				id: 34,
				date: '29.09.22',
				time: '17:18',
				title: 'Валаамское мгновение из Приозерска',
				persons: 4,
				amount: 26116,
				paymentType: 'Пожертвование',
				status: 'Отменено',
				qrcode: '',
			},
		],
		messages: [
			{
				id: 1,
				date: '21.02.2022',
				time: '15:00',
				title: 'Уведомление о переносе рейса',
				message: 'Ваш рейс был перенесен.',
				isNew: true,
			},
			{
				id: 2,
				date: '18.02.2022',
				time: '15:00',
				title: 'Запрос бронирования',
				message: 'Вы забронировали номер.',
				isNew: false,
			},
			{
				id: 3,
				date: '18.02.2022',
				time: '15:00',
				title: 'Уведомление о переносе рейса',
				message: 'Ваш рейс был перенесен.',
				isNew: true,
			},
			{
				id: 4,
				date: '16.02.2022',
				time: '15:00',
				title: 'Запрос бронирования',
				message: 'Вы забронировали номер.',
				isNew: false,
			},
			{
				id: 5,
				date: '13.02.2022',
				time: '15:00',
				title: 'Запрос бронирования',
				message: 'Вы забронировали номер.',
				isNew: false,
			},
			{
				id: 6,
				date: '13.02.2022',
				time: '15:00',
				title: 'Запрос бронирования',
				message: 'Вы забронировали номер.',
				isNew: false,
			},
			{
				id: 7,
				date: '11.02.2022',
				time: '15:00',
				title: 'Уведомление о переносе рейса',
				message: 'Ваш рейс был перенесен.',
				isNew: true,
			},
			{
				id: 8,
				date: '9.02.2022',
				time: '15:00',
				title: 'Запрос бронирования',
				message: 'Вы забронировали номер.',
				isNew: false,
			},
			{
				id: 9,
				date: '9.02.2022',
				time: '15:00',
				title: 'Уведомление о переносе рейса',
				message: 'Ваш рейс был перенесен.',
				isNew: true,
			},
			{
				id: 10,
				date: '7.02.2022',
				time: '15:00',
				title: 'Запрос бронирования',
				message: 'Вы забронировали номер.',
				isNew: false,
			},
			{
				id: 11,
				date: '2.02.2022',
				time: '15:00',
				title: 'Уведомление о переносе рейса',
				message: 'Ваш рейс был перенесен.',
				isNew: true,
			},
		],
	},
	getters: {
		getOrders: state => state.orders,
		getOrderById: state => (id: number) =>
			state.orders.find(order => order.id === id),
		getMessages: state => state.messages,
		getMessageById: state => (id: number) =>
			state.messages.find(order => order.id === id),
	},
	mutations: {},
	actions: {},
	modules: { auth },
})
